// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {custom} from '../models';
import {core} from '../models';

export function AddCredential(arg1:string,arg2:string,arg3:Record<string, string>):Promise<void>;

export function AddCustomService(arg1:custom.CustomServiceConfig):Promise<void>;

export function FetchAllProjects():Promise<Record<string, Array<core.ProjectInfo>>>;

export function FetchAllUsage():Promise<core.DashboardData>;

export function FetchUsage(arg1:string,arg2:string):Promise<core.UsageData>;

export function GetAllCredentials():Promise<Array<Record<string, string>>>;

export function GetAuthConfig(arg1:string):Promise<core.AuthConfig>;

export function GetAvailablePlatforms():Promise<Array<Record<string, string>>>;

export function GetCustomServices():Promise<Array<custom.CustomServiceConfig>>;

export function GetPlatformList():Promise<Array<string>>;

export function GetSettings():Promise<core.AppSettings>;

export function RemoveCredential(arg1:string,arg2:string):Promise<void>;

export function RemoveCustomService(arg1:string):Promise<void>;

export function TestConnection(arg1:string):Promise<Record<string, any>>;

export function UpdateCustomService(arg1:string,arg2:custom.CustomServiceConfig):Promise<void>;

export function UpdateSettings(arg1:core.AppSettings):Promise<void>;
