// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCredential'](arg1, arg2, arg3);
}

export function AddCustomService(arg1) {
  return window['go']['main']['App']['AddCustomService'](arg1);
}

export function FetchAllProjects() {
  return window['go']['main']['App']['FetchAllProjects']();
}

export function FetchAllUsage() {
  return window['go']['main']['App']['FetchAllUsage']();
}

export function FetchUsage(arg1, arg2) {
  return window['go']['main']['App']['FetchUsage'](arg1, arg2);
}

export function GetAllCredentials() {
  return window['go']['main']['App']['GetAllCredentials']();
}

export function GetAuthConfig(arg1) {
  return window['go']['main']['App']['GetAuthConfig'](arg1);
}

export function GetAvailablePlatforms() {
  return window['go']['main']['App']['GetAvailablePlatforms']();
}

export function GetCustomServices() {
  return window['go']['main']['App']['GetCustomServices']();
}

export function GetPlatformList() {
  return window['go']['main']['App']['GetPlatformList']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function RemoveCredential(arg1, arg2) {
  return window['go']['main']['App']['RemoveCredential'](arg1, arg2);
}

export function RemoveCustomService(arg1) {
  return window['go']['main']['App']['RemoveCustomService'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateCustomService(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomService'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
